spring.application.name=nutri

# Configurações de Conexão com o SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NutriPi;encrypt=true;trustServerCertificate=true
spring.datasource.username=nutrisa
spring.datasource.password=spypreto
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configurações do JPA/Hibernate
# Como usaremos o Flyway para criar as tabelas, deixamos o ddl-auto como 'validate' ou 'none'
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Flyway (Migrations)
spring.flyway.enabled=true